const express = require('express')
const app = express()
const port = process.env.PORT || 3000

console.log("Welcome")
console.log("----------------------------------")
console.log("Cyclic Default")
console.log(`Access Key: ${process.env.AWS_ACCESS_KEY_ID}`)
console.log(`Secret Key: ${process.env.AWS_SECRET_KEY}`)
console.log("----------------------------------")
console.log("----------------------------------")
console.log("My Env")
console.log(`Access Key: ${process.env.aws_access_key_id}`)
console.log(`Secret Key: ${process.env.aws_secret_access_key}`)
console.log("----------------------------------")
